package scm

import (
	"net/http"

	"github.com/paloaltonetworks/scm-go/common"
	"github.com/paloaltonetworks/scm-go/generated/config_setup"
	"github.com/paloaltonetworks/scm-go/generated/deployment_services"
	"github.com/paloaltonetworks/scm-go/generated/device_settings"
	"github.com/paloaltonetworks/scm-go/generated/identity_services"
	"github.com/paloaltonetworks/scm-go/generated/network_services"
	"github.com/paloaltonetworks/scm-go/generated/objects"
	"github.com/paloaltonetworks/scm-go/generated/security_services"
)

// This file is automatically generated. DO NOT EDIT.

func GetConfigSetupAPIClient(setupClient *Client) *config_setup.APIClient {
	config := config_setup.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return config_setup.NewAPIClient(config)
}

func GetDeploymentServicesAPIClient(setupClient *Client) *deployment_services.APIClient {
	config := deployment_services.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return deployment_services.NewAPIClient(config)
}

func GetDeviceSettingsAPIClient(setupClient *Client) *device_settings.APIClient {
	config := device_settings.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return device_settings.NewAPIClient(config)
}

func GetIdentityServicesAPIClient(setupClient *Client) *identity_services.APIClient {
	config := identity_services.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return identity_services.NewAPIClient(config)
}

func GetNetworkServicesAPIClient(setupClient *Client) *network_services.APIClient {
	config := network_services.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return network_services.NewAPIClient(config)
}

func GetObjectsAPIClient(setupClient *Client) *objects.APIClient {
	config := objects.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return objects.NewAPIClient(config)
}

func GetSecurityServicesAPIClient(setupClient *Client) *security_services.APIClient {
	config := security_services.NewConfiguration()
	config.Host = setupClient.GetHost()
	config.Scheme = "https"

	// Create a custom transport that handles JWT refresh
	jwtTransport := &JWTRefreshTransport{
		Wrapped:     setupClient.HttpClient.Transport,
		SetupClient: setupClient,
	}

	// Wrap with logging transport
	loggingTransport := &common.LoggingRoundTripper{
		Wrapped: jwtTransport,
	}

	// Create a new HTTP client with the transports
	httpClientWithJWT := &http.Client{
		Transport: loggingTransport,
		Timeout:   setupClient.HttpClient.Timeout,
	}

	config.HTTPClient = httpClientWithJWT

	return security_services.NewAPIClient(config)
}
